#Configs to run the program locally using RabbitMQ, save notification in DB and Databases+zipkin in a docker
#Configs to run the program locally using Kafka, save notification in DB and Databases+zipkin in a docker
spring:
  application:
    name: eureka-server
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8761

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: false
    register-with-eureka: false
