#Configs to run the program in a docker using RabbitMQ (saving notification in DB)
spring:
  application:
    name: eureka-server
  zipkin:
    base-url: http://zipkin:9411

server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false