#Configs to run the program locally using RabbitMQ, save notification in DB and Databases+zipkin in a docker
#Configs to run the program locally using Kafka, save notification in DB and Databases+zipkin in a docker
spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/customers/**

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true